name: short_app_front
description: A simple text-based SNS client.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # --- 状態管理 ---
  flutter_riverpod: ^2.5.1

  # --- ルーティング ---
  go_router: ^13.2.0

  # --- API通信 ---
  dio: ^5.4.1

  # --- UI/ユーティリティ ---
  google_fonts: ^6.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

  # --- 認証 (GCP/Firebase) ---
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
